# Generated by Django 4.2.6 on 2023-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IELTSer', '0003_correctanswersreading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cambridge', models.CharField(choices=[('Cambridge 1', 'c1'), ('Cambridge 2', 'c2')], max_length=20)),
                ('Test', models.CharField(choices=[('Test 1', 't1'), ('Test 2', 't2')], max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
