# Generated by Django 4.2.6 on 2023-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IELTSer', '0005_answersreading_question1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Listening', 'l'), ('Reading', 'r')], max_length=20)),
                ('Cambridge', models.CharField(choices=[('Cambridge 1', 'c1'), ('Cambridge 2', 'c2')], max_length=20)),
                ('Test', models.CharField(choices=[('Test 1', 't1'), ('Test 2', 't2')], max_length=20)),
                ('question1', models.CharField(max_length=20, null=True)),
                ('question2', models.CharField(max_length=20, null=True)),
                ('question3', models.CharField(max_length=20, null=True)),
                ('question4', models.CharField(max_length=20, null=True)),
                ('question5', models.CharField(max_length=20, null=True)),
                ('question6', models.CharField(max_length=20, null=True)),
                ('question7', models.CharField(max_length=20, null=True)),
                ('question8', models.CharField(max_length=20, null=True)),
                ('question9', models.CharField(max_length=20, null=True)),
                ('question10', models.CharField(max_length=20, null=True)),
                ('question11', models.CharField(max_length=20, null=True)),
                ('question12', models.CharField(max_length=20, null=True)),
                ('question13', models.CharField(max_length=20, null=True)),
                ('question14', models.CharField(max_length=20, null=True)),
                ('question15', models.CharField(max_length=20, null=True)),
                ('question16', models.CharField(max_length=20, null=True)),
                ('question17', models.CharField(max_length=20, null=True)),
                ('question18', models.CharField(max_length=20, null=True)),
                ('question19', models.CharField(max_length=20, null=True)),
                ('question20', models.CharField(max_length=20, null=True)),
                ('question21', models.CharField(max_length=20, null=True)),
                ('question22', models.CharField(max_length=20, null=True)),
                ('question23', models.CharField(max_length=20, null=True)),
                ('question24', models.CharField(max_length=20, null=True)),
                ('question25', models.CharField(max_length=20, null=True)),
                ('question26', models.CharField(max_length=20, null=True)),
                ('question27', models.CharField(max_length=20, null=True)),
                ('question28', models.CharField(max_length=20, null=True)),
                ('question29', models.CharField(max_length=20, null=True)),
                ('question30', models.CharField(max_length=20, null=True)),
                ('question31', models.CharField(max_length=20, null=True)),
                ('question32', models.CharField(max_length=20, null=True)),
                ('question33', models.CharField(max_length=20, null=True)),
                ('question34', models.CharField(max_length=20, null=True)),
                ('question35', models.CharField(max_length=20, null=True)),
                ('question36', models.CharField(max_length=20, null=True)),
                ('question37', models.CharField(max_length=20, null=True)),
                ('question38', models.CharField(max_length=20, null=True)),
                ('question39', models.CharField(max_length=20, null=True)),
                ('question40', models.CharField(max_length=20, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnswersReading',
        ),
    ]
