# Generated by Django 4.2.6 on 2023-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IELTSer', '0006_answers_delete_answersreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='Cambridge',
            field=models.CharField(choices=[('c1', 'Cambridge 1'), ('Cambridge 2', 'c2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='Test',
            field=models.CharField(choices=[('t1', 'Test 1'), ('Test 2', 't2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='answers',
            name='Type',
            field=models.CharField(choices=[('l', 'Listening'), ('r', 'Reading')], max_length=20),
        ),
    ]
