# Generated by Django 4.2.6 on 2023-11-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IELTSer', '0010_alter_answer_correctanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Test',
            field=models.CharField(choices=[('t1', 'Test 1'), ('t2', 'Test 2'), ('t3', 'Test 3'), ('t4', 'Test 4')], max_length=20),
        ),
    ]
